-- QuoteVault - Seed Quotes Data
-- Execute this SQL in your Supabase SQL Editor after running database-schema.sql
-- This will insert 120 quotes across 5 categories

INSERT INTO quotes (text, author, category) VALUES

-- Motivation (25 quotes)
('The only way to do great work is to love what you do.', 'Steve Jobs', 'Motivation'),
('Believe you can and you''re halfway there.', 'Theodore Roosevelt', 'Motivation'),
('Success is not final, failure is not fatal: it is the courage to continue that counts.', 'Winston Churchill', 'Motivation'),
('The future belongs to those who believe in the beauty of their dreams.', 'Eleanor Roosevelt', 'Motivation'),
('Don''t watch the clock; do what it does. Keep going.', 'Sam Levenson', 'Motivation'),
('The harder you work for something, the greater you''ll feel when you achieve it.', 'Unknown', 'Motivation'),
('Dream bigger. Do bigger.', 'Unknown', 'Motivation'),
('Don''t stop when you''re tired. Stop when you''re done.', 'Unknown', 'Motivation'),
('Wake up with determination. Go to bed with satisfaction.', 'Unknown', 'Motivation'),
('Do something today that your future self will thank you for.', 'Sean Patrick Flanery', 'Motivation'),
('Little things make big days.', 'Unknown', 'Motivation'),
('It''s going to be hard, but hard does not mean impossible.', 'Unknown', 'Motivation'),
('Don''t wait for opportunity. Create it.', 'Unknown', 'Motivation'),
('Sometimes we''re tested not to show our weaknesses, but to discover our strengths.', 'Unknown', 'Motivation'),
('The key to success is to focus on goals, not obstacles.', 'Unknown', 'Motivation'),
('Dream it. Believe it. Build it.', 'Unknown', 'Motivation'),
('Your limitation—it''s only your imagination.', 'Unknown', 'Motivation'),
('Great things never come from comfort zones.', 'Unknown', 'Motivation'),
('Success doesn''t just find you. You have to go out and get it.', 'Unknown', 'Motivation'),
('The harder you work, the luckier you get.', 'Gary Player', 'Motivation'),
('Don''t be afraid to give up the good to go for the great.', 'John D. Rockefeller', 'Motivation'),
('If you want to achieve greatness stop asking for permission.', 'Unknown', 'Motivation'),
('Things work out best for those who make the best of how things work out.', 'John Wooden', 'Motivation'),
('To live a creative life, we must lose our fear of being wrong.', 'Anonymous', 'Motivation'),
('Success is walking from failure to failure with no loss of enthusiasm.', 'Winston Churchill', 'Motivation'),

-- Love (24 quotes)
('Love is composed of a single soul inhabiting two bodies.', 'Aristotle', 'Love'),
('The best thing to hold onto in life is each other.', 'Audrey Hepburn', 'Love'),
('Love is not about how many days, months, or years you have been together. Love is about how much you love each other every single day.', 'Unknown', 'Love'),
('In all the world, there is no heart for me like yours.', 'Maya Angelou', 'Love'),
('I love you not only for what you are, but for what I am when I am with you.', 'Roy Croft', 'Love'),
('Love recognizes no barriers. It jumps hurdles, leaps fences, penetrates walls to arrive at its destination full of hope.', 'Maya Angelou', 'Love'),
('Where there is love there is life.', 'Mahatma Gandhi', 'Love'),
('Love is friendship that has caught fire.', 'Ann Landers', 'Love'),
('The greatest happiness of life is the conviction that we are loved; loved for ourselves, or rather, loved in spite of ourselves.', 'Victor Hugo', 'Love'),
('To love and be loved is to feel the sun from both sides.', 'David Viscott', 'Love'),
('Love is when the other person''s happiness is more important than your own.', 'H. Jackson Brown Jr.', 'Love'),
('Being deeply loved by someone gives you strength, while loving someone deeply gives you courage.', 'Lao Tzu', 'Love'),
('Love is the bridge between you and everything.', 'Rumi', 'Love'),
('The best and most beautiful things in this world cannot be seen or even heard, but must be felt with the heart.', 'Helen Keller', 'Love'),
('Love is an endless act of forgiveness. Forgiveness is the key to action and freedom.', 'Maya Angelou', 'Love'),
('Love doesn''t make the world go round. Love is what makes the ride worthwhile.', 'Franklin P. Jones', 'Love'),
('The giving of love is an education in itself.', 'Eleanor Roosevelt', 'Love'),
('Love is a promise; love is a souvenir, once given never forgotten, never let it disappear.', 'John Lennon', 'Love'),
('True love stories never have endings.', 'Richard Bach', 'Love'),
('Love is the only force capable of transforming an enemy into a friend.', 'Martin Luther King Jr.', 'Love'),
('Love is like the wind, you can''t see it but you can feel it.', 'Nicholas Sparks', 'Love'),
('At the touch of love everyone becomes a poet.', 'Plato', 'Love'),
('Love yourself first and everything else falls into line.', 'Lucille Ball', 'Love'),
('The heart wants what it wants. There''s no logic to these things.', 'Woody Allen', 'Love'),

-- Success (24 quotes)
('Success is not the key to happiness. Happiness is the key to success.', 'Albert Schweitzer', 'Success'),
('Success usually comes to those who are too busy to be looking for it.', 'Henry David Thoreau', 'Success'),
('The way to get started is to quit talking and begin doing.', 'Walt Disney', 'Success'),
('Don''t be afraid to give up the good to go for the great.', 'John D. Rockefeller', 'Success'),
('I find that the harder I work, the more luck I seem to have.', 'Thomas Jefferson', 'Success'),
('Success is not how high you have climbed, but how you make a positive difference to the world.', 'Roy T. Bennett', 'Success'),
('Opportunities don''t happen. You create them.', 'Chris Grosser', 'Success'),
('Success is not in what you have, but who you are.', 'Bo Bennett', 'Success'),
('The only limit to our realization of tomorrow will be our doubts of today.', 'Franklin D. Roosevelt', 'Success'),
('The secret of success is to do the common thing uncommonly well.', 'John D. Rockefeller Jr.', 'Success'),
('Success is liking yourself, liking what you do, and liking how you do it.', 'Maya Angelou', 'Success'),
('Try not to become a man of success. Rather become a man of value.', 'Albert Einstein', 'Success'),
('Don''t aim for success if you want it; just do what you love and believe in, and it will come naturally.', 'David Frost', 'Success'),
('Success seems to be connected with action. Successful people keep moving.', 'Conrad Hilton', 'Success'),
('The road to success and the road to failure are almost exactly the same.', 'Colin R. Davis', 'Success'),
('Success is walking from failure to failure with no loss of enthusiasm.', 'Winston S. Churchill', 'Success'),
('I never dreamed about success, I worked for it.', 'Estée Lauder', 'Success'),
('Success is not measured by what you accomplish, but by the opposition you have encountered.', 'Orison Swett Marden', 'Success'),
('The only place where success comes before work is in the dictionary.', 'Vidal Sassoon', 'Success'),
('Success is the sum of small efforts repeated day in and day out.', 'Robert Collier', 'Success'),
('Fall seven times and stand up eight.', 'Japanese Proverb', 'Success'),
('Success is how high you bounce when you hit bottom.', 'George S. Patton', 'Success'),
('The difference between successful people and others is how long they spend time feeling sorry for themselves.', 'Barbara Corcoran', 'Success'),
('Success is doing ordinary things extraordinarily well.', 'Jim Rohn', 'Success'),

-- Wisdom (24 quotes)
('The only true wisdom is in knowing you know nothing.', 'Socrates', 'Wisdom'),
('The fool doth think he is wise, but the wise man knows himself to be a fool.', 'William Shakespeare', 'Wisdom'),
('Knowing yourself is the beginning of all wisdom.', 'Aristotle', 'Wisdom'),
('Turn your wounds into wisdom.', 'Oprah Winfrey', 'Wisdom'),
('The journey of a thousand miles begins with one step.', 'Lao Tzu', 'Wisdom'),
('We cannot solve our problems with the same thinking we used when we created them.', 'Albert Einstein', 'Wisdom'),
('The unexamined life is not worth living.', 'Socrates', 'Wisdom'),
('Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.', 'Rumi', 'Wisdom'),
('The only way to make sense out of change is to plunge into it, move with it, and join the dance.', 'Alan Watts', 'Wisdom'),
('In the middle of difficulty lies opportunity.', 'Albert Einstein', 'Wisdom'),
('Wisdom is not a product of schooling but of the lifelong attempt to acquire it.', 'Albert Einstein', 'Wisdom'),
('The wise man does at once what the fool does finally.', 'Baltasar Gracián', 'Wisdom'),
('Knowledge speaks, but wisdom listens.', 'Jimi Hendrix', 'Wisdom'),
('The invariable mark of wisdom is to see the miraculous in the common.', 'Ralph Waldo Emerson', 'Wisdom'),
('The art of being wise is knowing what to overlook.', 'William James', 'Wisdom'),
('By three methods we may learn wisdom: First, by reflection, which is noblest; Second, by imitation, which is easiest; and third by experience, which is the bitterest.', 'Confucius', 'Wisdom'),
('Patience is the companion of wisdom.', 'Saint Augustine', 'Wisdom'),
('The doors of wisdom are never shut.', 'Benjamin Franklin', 'Wisdom'),
('The wise man bridges the gap by laying out the path by means of which he can get from where he is to where he wants to go.', 'J. P. Morgan', 'Wisdom'),
('Common sense in an uncommon degree is what the world calls wisdom.', 'Samuel Taylor Coleridge', 'Wisdom'),
('Never mistake knowledge for wisdom. One helps you make a living; the other helps you make a life.', 'Eleanor Roosevelt', 'Wisdom'),
('The saddest aspect of life right now is that science gathers knowledge faster than society gathers wisdom.', 'Isaac Asimov', 'Wisdom'),
('A wise man can learn more from a foolish question than a fool can learn from a wise answer.', 'Bruce Lee', 'Wisdom'),
('Honesty is the first chapter in the book of wisdom.', 'Thomas Jefferson', 'Wisdom'),

-- Humor (23 quotes)
('I''m not superstitious, but I am a little stitious.', 'Michael Scott', 'Humor'),
('The difference between stupidity and genius is that genius has its limits.', 'Albert Einstein', 'Humor'),
('Before you marry a person, you should first make them use a computer with slow Internet to see who they really are.', 'Will Ferrell', 'Humor'),
('I always arrive late at the office, but I make up for it by leaving early.', 'Charles Lamb', 'Humor'),
('The road to success is dotted with many tempting parking spaces.', 'Will Rogers', 'Humor'),
('If you think you are too small to make a difference, try sleeping with a mosquito.', 'Dalai Lama', 'Humor'),
('Get your facts first, then you can distort them as you please.', 'Mark Twain', 'Humor'),
('I''m writing a book. I''ve got the page numbers done.', 'Steven Wright', 'Humor'),
('The elevator to success is out of order. You''ll have to use the stairs, one step at a time.', 'Joe Girard', 'Humor'),
('I used to think I was indecisive, but now I''m not so sure.', 'Unknown', 'Humor'),
('Common sense is like deodorant. The people who need it most never use it.', 'Unknown', 'Humor'),
('My fake plants died because I did not pretend to water them.', 'Mitch Hedberg', 'Humor'),
('A day without sunshine is like, you know, night.', 'Steve Martin', 'Humor'),
('When life gives you lemons, squirt someone in the eye.', 'Cathy Guisewite', 'Humor'),
('The trouble with having an open mind, of course, is that people will insist on coming along and trying to put things in it.', 'Terry Pratchett', 'Humor'),
('Age is of no importance unless you''re a cheese.', 'Billie Burke', 'Humor'),
('I don''t believe in astrology; I''m a Sagittarius and we''re skeptical.', 'Arthur C. Clarke', 'Humor'),
('Inside me there''s a thin person struggling to get out, but I can usually sedate him with four or five cupcakes.', 'Bob Thaves', 'Humor'),
('Wine is constant proof that God loves us and loves to see us happy.', 'Benjamin Franklin', 'Humor'),
('People say nothing is impossible, but I do nothing every day.', 'A.A. Milne', 'Humor'),
('When life gives you lemons, make lemonade. Then find someone whose life gave them vodka and have a party.', 'Ron White', 'Humor'),
('I''m not lazy, I''m on energy saving mode.', 'Unknown', 'Humor'),
('Reality is the leading cause of stress among those in touch with it.', 'Lily Tomlin', 'Humor');

-- Success message
DO $$
DECLARE
    quote_count INTEGER;
BEGIN
    SELECT COUNT(*) INTO quote_count FROM quotes;
    RAISE NOTICE 'Successfully inserted % quotes!', quote_count;
    RAISE NOTICE 'Categories: Motivation, Love, Success, Wisdom, Humor';
    RAISE NOTICE 'Database is now ready for QuoteVault app!';
END $$;
